### ISSUE TITLE
Fixed:  DEPRECATION WARNING: 

### ISSUE THREAD

**Issue by MarczalTSIGP** [MarczalTSIGP/SGTCC#291]
DEPRECATION WARNING: #extension_whitelist is deprecated, use #extension_allowlist instead. (called from block (4 levels) in <main> at /__w/SGTCC/SGTCC/spec/factories/orientations.rb:83)
DEPRECATION WARNING: #extension_whitelist is deprecated, use #extension_allowlist instead. (called fr

Failures:

  1) Document::sign #sign when signs the signature of the term of accept institution signs the document of the term of accept institution
     Failure/Error: page.find(options[:in], wait: 10).has_content?(content.to_s)

     Capybara::ElementNotFound:
       Unable to find css "div.swal-text"
     # ./spec/support/matchers/have_message.rb:3:in `block (2 levels) in <main>'
     # ./spec/features/external_members/documents/term_of_accept_institution/documents_sign_spec.rb:23:in `block (4 levels) in <main>'

Finished in 6 minutes 48 seconds (files took 1.77 seconds to load)
920 examples, 1 failure

Failed examples:

rspec ./spec/features/external_members/documents/term_of_accept_institution/documents_sign_spec.rb:17 # Document::sign #sign when signs the signature of the term of accept institution signs the document of the term of accept institution

**Comment by MarczalTSIGP** [comment]
Fixed.
